### ISSUE TITLE
Mistake in figure 3-17 - missing 'C6'

### ISSUE THREAD

**Issue by ZvikaZ** [progit/progit2#439] opened 2015-10-27 13:19 UTC
In figure 3-17 there are 2 'C5' commits, instead of 'C5' and 'C6' at the end.

**Comment by crd** [comment] 2015-10-31 12:53
Interesting: This image was updated here nearly a year ago -- see commit https://github.com/progit/progit2/commit/3491527b33251fcacd8d2964bf7fb5e0f1cfe455.

When logging issues against progit2 it's always best to check the latest version of the pdf here: https://progit.org to try to find root cause.  For whatever reason, the html version of the book at http://git-scm.com/book isn't updated consistently. Perhaps open an issue with https://github.com/git/git-scm.com?

I recommend closing this issue.

**Comment by ben** [comment] 2015-11-01 15:10
Thanks for catching this, @crd.

**Closed by ben** 2015-11-01 15:10 UTC
