### ISSUE TITLE
Should break the lines below:

### ISSUE THREAD

**Issue by LeonardLaszlo** [progit/progit2#627] opened 2016-07-20 16:33 UTC
git config --global core.editor "'C:/Program Files/Notepad++/notepad++.exe' -multiInst -no
git config --global core.editor "'C:/Program Files (x86)/Notepad++/notepad++.exe' -multiIn

The lines are located on page 41 of the pdf version.
I use Atril Document Viewer 1.10.2.

**Comment by YueLinHo** [comment] 2016-07-21 01:57
![image](https://cloud.githubusercontent.com/assets/5831804/17008916/63ee15e8-4f28-11e6-9e42-5bd86af5e4d8.png)

**Comment by YueLinHo** [comment] 2016-07-21 01:58
![image](https://cloud.githubusercontent.com/assets/5831804/17009041/94d9adba-4f29-11e6-8142-7c2b99eb7a93.png)

**Comment by nobozo** [comment] 2016-07-21 04:34
This really isn't part of the issue, but has anyone ever
noticed how these two commands are reversed? That is, the
first 'git config' lines is actually for x64 and the second is
for x32.

Jon Forrest

**Comment by YueLinHo** [comment] 2016-07-21 05:10
> That is, the first 'git config' lines is actually for x64 and the second is for x32.

@nobozo No, that is not true. They are correct. See issue #443

**Comment by nobozo** [comment] 2016-07-21 05:14
On 7/20/2016 10:10 PM, Yue Lin Ho wrote:
>     That is, the first 'git config' lines is actually for x64 and the second is for x32.
>
> @nobozo <https://github.com/nobozo> No, that is not true. They are correct. See issue #443
> <https://github.com/progit/progit2/issues/443>

Good point. However, on Windows 10 (64-bit) this is incorrect. My notepad
is in C:\Windows\System32. I don't  have a 32-bit version to check.

Jon

**Comment by nobozo** [comment] 2016-07-21 05:39
On 7/20/2016 10:10 PM, Yue Lin Ho wrote:
>     That is, the first 'git config' lines is actually for x64 and the second is for x32.

Please ignore my stupid previous comment. I was looking at notepad, not notepad++.

1000 apologies.

Jon Forrest

**Comment by YueLinHo** [comment] 2016-07-21 05:43
@nobozo Let's delete our irrelevant comments?

**Comment by LeonardLaszlo** [comment] 2016-07-21 09:00
@nobozo If you have a non-related problem you should open a new issue for it!

**Comment by LeonardLaszlo** [comment] 2016-07-22 15:01
This problem occurs a lot of times in the pdf version.

**Comment by YueLinHo** [comment] 2016-07-25 01:08
IIRC(not pretty sure), this may be a duplicate.

**Comment by jnavila** [comment] 2016-07-25 05:06
Unless we break the line "by hand", I don't see any solution.

**Comment by HonkingGoose** [comment] 2019-04-01 21:32
@jnavila this seems similar to #133 which we closed. Also the picture from @YueLinHo is a duplicate of https://github.com/progit/progit2/issues/133#issuecomment-187465638

**Comment by YueLinHo** [comment] 2019-04-02 02:01
I checked https://github.com/progit/progit2/releases/download/2.1.140/progit.pdf on page 22
![image](https://user-images.githubusercontent.com/5831804/55370731-132bb980-552e-11e9-91f8-7ac5564807af.png)

Can be closed!

**Closed** 2019-04-02 07:10 UTC
