### ISSUE TITLE
git bash - git clone error: unable to create file .... Invalid argument

### ISSUE THREAD

**Issue by killrazor** [progit/progit2#690] opened 2016-12-14 16:24 UTC
While using git bash (2.11.0) 64-bit version of Git for Windows.

I attempted to clone three remote repos. Only one was successful.

The other two gave me erorrs like:

`remote: Counting objects: 5876, done.`
`remote: Compressing objects: 100% (4026/4026), done.`
`remote: Total 5876 (delta 2082), reused 5330 (delta 1776)`
`Receiving objects: 100% (5876/5876), 108.31 MiB | 1.79 MiB/s, done.`
`Resolving deltas: 100% (2082/2082), done.`
`error: unable to create file html/v3/css/main.css?v=1.2: Invalid argument`
`error: unable to create file prod/html/v3/css/main.css?v=1.2: Invalid argument`
`error: unable to create file prod/html/vc/css/main.css?v=1.2: Invalid argument`
`Checking out files: 100% (5040/5040), done.`
`fatal: unable to checkout working tree`
`warning: Clone succeeded, but checkout failed.`
`You can inspect what was checked out with 'git status' and retry the checkout with 'git checkout -f HEAD`

I believe the `?` in the filename is the issue. The other failed repo had various other special characters that looked like they should have been okay. Should I add those files to `.gitignore` and take them off the repo or is there some other workaround? Obviously I would just change the file name if that was an option.

**Comment by jnavila** [comment] 2016-12-14 18:21
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

If you need help with using git, you can ask the [community](https://git-scm.com/community)

**Comment by ben** [comment] 2016-12-14 19:07
Agreed. I googled a bit and found [a blog post that might help you](http://maian.org/blog/2014/01/git-error-unable-to-create-file-invalid-argument/), but otherwise we can't do anything about the root cause here. Closing for now.

**Closed by ben** 2016-12-14 19:07 UTC
