### ISSUE TITLE
Mistake in figure 3-9 - swapped branches

### ISSUE THREAD

**Issue by ZvikaZ** [progit/progit2#438] opened 2015-10-27 13:16 UTC
There is a mistake in figure 3-9.
According to previous figures, and to the code just below it, 87ab2 should be 'testing' and  c2b9e should be 'master'

**Comment by crd** [comment] 2015-10-31 13:11
This issue is a duplicate of https://github.com/progit/progit2/issues/136 which was subsequently fixed with https://github.com/progit/progit2/commit/87254184fd3642148c284df68c59ae20751ca44a. It seems like   the outdated html content at git-scm.com is the source of the majority of issues opened against progit2.

**Comment by YueLinHo** [comment] 2016-04-11 02:08
So, this issue should be closed as duplicate.

**Closed** 2016-04-11 16:28 UTC
