### ISSUE TITLE
The centralized version control diagram image is missing

### ISSUE THREAD

**Issue by ahmad88me** [progit/progit2#328] opened 2015-07-13 11:14 UTC
https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control

**Comment by rmzelle** [comment] 2015-08-07 20:19
Duplicate of #315.

**Comment by YueLinHo** [comment] 2016-03-16 03:22
In fact, dulicate #294. And that figure shows now.

**Closed** 2016-03-16 08:26 UTC
