### ISSUE TITLE
Double-escaped angle brackets etc.?

### ISSUE THREAD

**Issue by JonathanHayward** [progit/progit2#451] opened 2015-11-17 14:26 UTC
I quote one of many webpages on git-scr.com, in this case https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things :

    $ git add *
    $ git status
    On branch master
    Changes to be committed:
      (use "git reset HEAD &amp;lt;file&amp;gt;..." to unstage)

        renamed:    README.md -&amp;gt; README
        modified:   CONTRIBUTING.md

Could the level of escaping be done more appropriately so that what are meant as angle brackets are visible as such in code blocks included in the text?

**Comment by jnavila** [comment] 2015-11-17 14:32
This is duplicate of #371

**Closed by jnavila** 2015-11-17 14:32 UTC
