### ISSUE TITLE
git stash pop -q in 2.24.0

### ISSUE THREAD

**Issue by hiroyuki-okazaki-shi** [progit/progit2#1330] opened 2019-11-12 03:10 UTC
If you run the following command
All files are deleted in the stage.

commands:
 git stash
 git stash pop -q

version:
 git version 2.24.0.windows.2
 windows 10 pro 1809

**Comment by ben** [comment] 2019-11-12 17:22
Can you copy/paste an entire terminal session where this happens? I'd love to be able to reproduce.

**Comment by hiroyuki-okazaki-shi** [comment] 2019-11-13 07:53
terminal session:

D:\temp>md test1

D:\temp>cd test1

D:\temp\test1>git init
Initialized empty Git repository in D:/temp/test1/.git/

D:\temp\test1>echo test1>text.txt

D:\temp\test1>git add text.txt

D:\temp\test1>git commit -m commit1
[master (root-commit) 38a4da6] commit1
 1 file changed, 1 insertion(+)
 create mode 100644 text.txt

D:\temp\test1>echo test2>>text.txt

D:\temp\test1>git stash
Saved working directory and index state WIP on master: 38a4da6 commit1

D:\temp\test1>git stash pop -q

D:\temp\test1>git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        deleted:    text.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        text.txt

D:\temp\test1>dir /b
text.txt

**Comment by ben** [comment] 2019-11-14 22:07
Wow, that does seem like serious behavior. It's not reproducible on my mac here, and we don't recommend the use of that flag, so I don't think we've got a bug in the book source. You should report this to the Git maintainers, I believe the right way to do that is using [the mailing list](https://git-scm.com/community).

Closing this out, since there's nothing we can do in this repo to fix the problem.

**Closed by ben** 2019-11-14 22:07 UTC
