### ISSUE TITLE
Figure 3-9 references broken - 3.1 Branches in a Nutshell

### ISSUE THREAD

**Issue by haripetrov** [progit/progit2#313] opened 2015-05-29 12:39 UTC
Probably this is related with #291 but still [this problem](http://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell) has to be reported:
![progit2_figure_3_9](https://cloud.githubusercontent.com/assets/1268290/7882694/d574a506-0618-11e5-80d2-75d843bee379.png)

**Comment by PinoTsao** [comment] 2015-06-02 08:24
the figure 3-9, As I understand, the '87ab2' & 'c2b9e' should be switched, isn`t it?
In the 1st edtion of the book, this figure is exactly looks as what I understand, but in 2nd edtion, don`t know why

**Comment by AnnabellChan** [comment] 2015-08-21 03:46
I'm also confused by the Fig.  3-8 & Fig. 3-9 in Ch 3-1. Since the modification was made on master branch，it should be `c2b9e` instead of `87ab2` pointed by master branch.

**Comment by lighthunt** [comment] 2015-09-09 08:28
+1 -- The issue is present on web as well: https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell
I was very confused as well when reading this, "Why the branch pointers to commits are swapped?" I couldn't find a reasonable explanation why it is so until I realized the picture must be wrong. It does not correspond to to the example in the chapter and the later git log output (which appears to be correct and corresponding to the examle in my view):
$ git log --oneline --decorate --graph --all
* c2b9e (HEAD, master) made other changes
| * 87ab2 (testing) made a change

**Comment by lighthunt** [comment] 2015-09-12 06:45
It looks fixed in sources https://github.com/progit/progit2/blob/master/book/03-git-branching/images/advance-master.png
 pdf/html.zip/.mobi versions are fine but the https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell has got and out-dated build ....

**Comment by YueLinHo** [comment] 2016-03-16 03:17
I think this is a duplicate to #291 which talking about broken link of figure.

**Comment by HonkingGoose** [comment] 2019-04-02 10:06
I think this is fixed in the current version of: https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell

The pictures look okay to me. Both testing and master have divergent history at the end of the sequence. In the in-between picture the pointer points to the correct commits for either branch. Also the pictures seem to follow what happens in the text too.

But maybe somebody else can check this, and correct me if I'm worng... :smile:

**Comment by jnavila** [comment] 2019-04-02 20:39
The figure is fixed.

**Closed by jnavila** 2019-04-02 20:39 UTC
