### ISSUE TITLE
x86 and x64 Paths are switched

### ISSUE THREAD

**Issue by Qwampa2** [progit/progit2#732] opened 2017-03-02 09:06 UTC
I think the x86 and x64 Paths are Switched at the following page:
https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup
Take a quick look

**Comment by YueLinHo** [comment] 2017-03-02 09:09
Duplicate of issue #443

**Closed** 2017-03-02 09:16 UTC
